User-story/2342-clean-up-padding-in-inner-frames
OpenTrafficCam/OTAnalytics pull request #286
Opened 2023-07-28 00:16 UTC by martinbaerwolff

OP#2342

2023-08-04 07:54 UTC, briemla commented on OTAnalytics/plugin_ui/customtkinter_gui/custom_containers.py
> +    #     self.grid_rowconfigure(0, weight=0, minsize=0)
Could this code be removed?

2023-08-04 08:10 UTC, briemla requested changes

2023-08-04 08:10 UTC, briemla commented on OTAnalytics/plugin_ui/customtkinter_gui/frame_project.py
> +        self.PROJECT: str = "Project"
`self.PROJECT` looks more like `self.title`

2023-08-04 08:10 UTC, briemla commented on OTAnalytics/plugin_ui/customtkinter_gui/frame_tracks.py
> +        # self.label = CTkLabel(master=self, text="Tracks")
Could this code be removed?

2023-08-04 08:10 UTC, briemla commented on OTAnalytics/plugin_ui/customtkinter_gui/frame_videos.py
> +        # )
Could this code be removed?

2023-08-04 08:10 UTC, briemla commented on OTAnalytics/plugin_ui/customtkinter_gui/gui.py
> +            # fg_color=self._app.cget("fg_color"),
Could this code be removed?

2023-08-04 08:10 UTC, briemla commented on OTAnalytics/plugin_ui/customtkinter_gui/gui.py
> +        self._content.grid(row=0, column=1, padx=PADX, pady=PADY + 13, sticky=STICKY)
13 as magic number might be bad?
Can we extract it into a constant?

2023-08-04 11:06 UTC, martinbaerwolff commented
Also had a look at the whole new design on windows, everything looks fine

2023-08-11 10:22 UTC, briemla approved these changes

2023-08-11 10:22 UTC, merged