User story/2558 create shapely geometry cache to speed up intersection
OpenTrafficCam/OTAnalytics pull request #298
Opened 2023-08-09 10:01 UTC by randy-seng

2023-08-14 08:07 UTC, briemla requested changes
Looks good. Just a few things.

2023-08-14 11:05 UTC, randy-seng commented on tests/OTAnalytics/plugin_intersect/test_shapely_intersect.py
> +            (0.0, 0.0),
Exactly, points sitting on the boundary of a polygon are not considered to be within the polygon, and thus evaluate to `False`

2023-08-14 14:34 UTC, randy-seng commented on OTAnalytics/adapter_intersect/intersect.py
> +from OTAnalytics.plugin_intersect.shapely_intersect import ShapelyIntersector
It is not necessary. Actually we don't need to introduce a new interface. The adapter class only contains delegation code.  
It handles the mapping of domain objects to shapely objects and vice versa. 
The delegation logic of the adapter class is now directly integrated in the `ShapelyIntersector`.

2023-08-18 08:26 UTC, briemla approved these changes

2023-08-18 08:26 UTC, merged